version: "3.4"
services:

  api:
    build:
      context: ./Server # Specify the path to the client directory
      dockerfile: Dockerfile # The Dockerfile for the client
    container_name: node_c
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - ./Server:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:  
      context: ./Client/CRUD
      dockerfile: Dockerfile
    container_name: vue_c
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - VITE_DEV_BASE_URL=http://localhost:4000/api
    volumes:
      - type: bind
        source: ./Client/CRUD
        target: /app
    tty: true

  game:
    build:
      context: ./Game/rpg-game # Specify the path to the client directory
      dockerfile: Dockerfile # The Dockerfile for the client
    container_name: game_c
    environment:
      - NODE_ENV=production
      - VITE_SERVER_URL=http://localhost:3000
      - MONGO_SERVER=mongodb://mongo:27017/rpg_prod
    ports:
      - "3000:3000"
    volumes:
      - ./Game:/rpg-game
  
volumes:
  mongo_data:
    driver: local
    name: mongo-data