name = 'My RPG Game'

modules = [
   '@rpgjs/save',
   '@rpgjs/plugin-emotion-bubbles',
    './src/modules/main',
    './src/modules/login_module',
    './src/modules/menu_module',
    './src/modules/edit_events_module',
    './src/modules/chat_module'
]

[login_module]
    mongodb = "mongodb://127.0.0.1:27017/test"

[start]
    graphic = 'hero'
    hitbox = [16, 16]
