name = 'My Game'

modules = [
   'rpgjs-inventory',
	'./spritesheets',
	'rpgjs-character-select',
	'./menu_module',
	'./login_module',
	'./main',
    './loadEvents'
]

spritesheetDirectories = [
    'lpc/heads',
    'lpc/bodies',
    'lpc/accessories',
    'lpc/torso',
    'lpc/legs',
    'lpc/hair',
    'lpc/ears'
]

[login_module]
	mongodb ="mongodb://127.0.0.1:27017/rpg_dev"


[characterSelect]
  	actors = [
		'human',
		'elf'
    ]


[inputs.action]
    name = "action"
    bind = ["space", "enter", "click"]

[inputs.ctrl]
    name = "ctrl"
    bind = "ctrl"

[inputs.attack]
    name = "attack"
    bind = "q"

[inputs.defend]
    name = "defend"
    bind = "w"

[inputs.m]
    name = "map"
    bind = "m"

[inputs.n]
    name = "inventory"
    bind = "n"


